/* test_sprites header file
 *  Generated by bss.pl.  Do not edit this file unless you want PAIN
 *  bss.pl is (c)2011 Scott Lawrence, Trilobyte
 *
 *  Include this file in *one* .m file.
 *
 *  Pseudoishcode to render a sprite:

void drawSprite( int idx )
{
	// bounds check the INDEX (sprite number)
	if( idx > count_test_sprites || idx < 0 ) return;

	// GL stuff (once per series of sprites)
	glEnableClientState(GL_VERTEX_ARRAY);
	glEnableClientState(GL_TEXTURE_COORD_ARRAY);
	glBindTexture(GL_TEXTURE_2D, theGLUintOfThePngGeneratedLoadedIn );

	// set the source position in the sheet.
	glTexCoordPointer( 2, GL_FLOAT, 0, &spr_test_sprites[idx *8] ); // source in sheet

	// build the "backwards N" for the screen: x0, y0, z0,  x1, y1, z1,  etc.
	GLfloat destVerts[12]; // backwards N
	GLfloat w = sprw_test_sprites[idx];
	GLfloat h = sprh_test_sprites[idx];

	destVerts[0] = 0.0;             destVerts[1] = 0.0;             destVerts[2] = 0.0;
	destVerts[3] = 0.0;             destVerts[4] = h;               destVerts[5] = 0.0;
	destVerts[6] = w;               destVerts[7] = 0.0;             destVerts[8] = 0.0;
	destVerts[9] = w;               destVerts[10] = h;              destVerts[11] = 0.0;

	// set the pointer
	glVertexPointer( 3, GL_FLOAT, 0, destVerts ); // position on screen

	// draw it!
	glColor4f( 1.0, 1.0, 1.0, 1.0 ); // adjust this to attenuate channels R, G, B, A
	glDrawArrays(GL_TRIANGLE_STRIP, 0, 4);

	// GL stuff (once per series of sprites
	glBindTexture(GL_TEXTURE_2D, 0);	
	glDisableClientState(GL_VERTEX_ARRAY);
	glDisableClientState(GL_TEXTURE_COORD_ARRAY);
}

 *
 */

#define count_test_sprites 20

GLfloat spr_test_sprites[20 * 8] = {
      0.0f/512.0f,   0.0f/256.0f,    0.0f/512.0f,  64.0f/256.0f,   64.0f/512.0f,   0.0f/256.0f,   64.0f/512.0f,  64.0f/256.0f,   /*   0: testImgs1/appicon64.gif */
     65.0f/512.0f,   0.0f/256.0f,   65.0f/512.0f,  34.0f/256.0f,   99.0f/512.0f,   0.0f/256.0f,   99.0f/512.0f,  34.0f/256.0f,   /*   1: testImgs1/build.gif */
    100.0f/512.0f,   0.0f/256.0f,  100.0f/512.0f,  34.0f/256.0f,  134.0f/512.0f,   0.0f/256.0f,  134.0f/512.0f,  34.0f/256.0f,   /*   2: testImgs1/buildandplay.gif */
    135.0f/512.0f,   0.0f/256.0f,  135.0f/512.0f,  34.0f/256.0f,  169.0f/512.0f,   0.0f/256.0f,  169.0f/512.0f,  34.0f/256.0f,   /*   3: testImgs1/clock.gif */
    170.0f/512.0f,   0.0f/256.0f,  170.0f/512.0f,  34.0f/256.0f,  204.0f/512.0f,   0.0f/256.0f,  204.0f/512.0f,  34.0f/256.0f,   /*   4: testImgs1/clock2.gif */
    205.0f/512.0f,   0.0f/256.0f,  205.0f/512.0f,  34.0f/256.0f,  239.0f/512.0f,   0.0f/256.0f,  239.0f/512.0f,  34.0f/256.0f,   /*   5: testImgs1/datain.gif */
    240.0f/512.0f,   0.0f/256.0f,  240.0f/512.0f,  34.0f/256.0f,  274.0f/512.0f,   0.0f/256.0f,  274.0f/512.0f,  34.0f/256.0f,   /*   6: testImgs1/dataout.gif */
    275.0f/512.0f,   0.0f/256.0f,  275.0f/512.0f,  34.0f/256.0f,  309.0f/512.0f,   0.0f/256.0f,  309.0f/512.0f,  34.0f/256.0f,   /*   7: testImgs1/find.gif */
    310.0f/512.0f,   0.0f/256.0f,  310.0f/512.0f,  34.0f/256.0f,  344.0f/512.0f,   0.0f/256.0f,  344.0f/512.0f,  34.0f/256.0f,   /*   8: testImgs1/findnext.gif */
    345.0f/512.0f,   0.0f/256.0f,  345.0f/512.0f,  34.0f/256.0f,  365.0f/512.0f,   0.0f/256.0f,  365.0f/512.0f,  34.0f/256.0f,   /*   9: testImgs1/spacer.gif */
      0.0f/512.0f,  65.0f/256.0f,    0.0f/512.0f,  99.0f/256.0f,   34.0f/512.0f,  65.0f/256.0f,   34.0f/512.0f,  99.0f/256.0f,   /*  10: testImgs2/floppy.gif */
     35.0f/512.0f,  65.0f/256.0f,   35.0f/512.0f,  99.0f/256.0f,   69.0f/512.0f,  65.0f/256.0f,   69.0f/512.0f,  99.0f/256.0f,   /*  11: testImgs2/playfloppy.gif */
     70.0f/512.0f,  65.0f/256.0f,   70.0f/512.0f,  99.0f/256.0f,  104.0f/512.0f,  65.0f/256.0f,  104.0f/512.0f,  99.0f/256.0f,   /*  12: testImgs2/recordfloppy.gif */
      0.0f/512.0f, 100.0f/256.0f,    0.0f/512.0f, 134.0f/256.0f,   34.0f/512.0f, 100.0f/256.0f,   34.0f/512.0f, 134.0f/256.0f,   /*  13: testImgs3/pause.gif */
     35.0f/512.0f, 100.0f/256.0f,   35.0f/512.0f, 134.0f/256.0f,   69.0f/512.0f, 100.0f/256.0f,   69.0f/512.0f, 134.0f/256.0f,   /*  14: testImgs3/play.gif */
     70.0f/512.0f, 100.0f/256.0f,   70.0f/512.0f, 134.0f/256.0f,  104.0f/512.0f, 100.0f/256.0f,  104.0f/512.0f, 134.0f/256.0f,   /*  15: testImgs3/reset.gif */
    105.0f/512.0f, 100.0f/256.0f,  105.0f/512.0f, 134.0f/256.0f,  139.0f/512.0f, 100.0f/256.0f,  139.0f/512.0f, 134.0f/256.0f,   /*  16: testImgs3/resetpause.gif */
    140.0f/512.0f, 100.0f/256.0f,  140.0f/512.0f, 134.0f/256.0f,  174.0f/512.0f, 100.0f/256.0f,  174.0f/512.0f, 134.0f/256.0f,   /*  17: testImgs3/step.gif */
    175.0f/512.0f, 100.0f/256.0f,  175.0f/512.0f, 134.0f/256.0f,  209.0f/512.0f, 100.0f/256.0f,  209.0f/512.0f, 134.0f/256.0f,   /*  18: testImgs3/stop.gif */
    210.0f/512.0f, 100.0f/256.0f,  210.0f/512.0f, 134.0f/256.0f,  244.0f/512.0f, 100.0f/256.0f,  244.0f/512.0f, 134.0f/256.0f,   /*  19: testImgs3/yellowbox.gif */

};

GLfloat sprw_test_sprites[20] = {
65, 35, 35, 35, 35, 35, 35, 35, 35, 21, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35
};

GLfloat sprh_test_sprites[20] = {
65, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35
};

